// <auto-generated />
using System;
using System.Collections.Generic;
using LingoHop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LingoHop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LingoHopDbContext))]
    [Migration("20260728080221_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lingohop")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LingoHop.Domain.Decks.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<string>("Example")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("example");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("term");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("translation");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Mastery", "LingoHop.Domain.Decks.Card.Mastery#CardMastery", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CorrectStreak")
                                .HasColumnType("integer")
                                .HasColumnName("correct_streak");

                            b1.Property<DateTimeOffset?>("LastReviewedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_reviewed_at_utc");

                            b1.Property<int>("TimesKnown")
                                .HasColumnType("integer")
                                .HasColumnName("times_known");

                            b1.Property<int>("TimesSeen")
                                .HasColumnType("integer")
                                .HasColumnName("times_seen");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeckId", "Term")
                        .IsUnique()
                        .HasDatabaseName("ix_cards_deck_id_term");

                    b.ToTable("cards", "lingohop");
                });

            modelBuilder.Entity("LingoHop.Domain.Decks.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_decks_owner_id");

                    b.ToTable("decks", "lingohop");
                });

            modelBuilder.Entity("LingoHop.Domain.Study.SessionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at_utc");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<bool?>("Known")
                        .HasColumnType("boolean")
                        .HasColumnName("known");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_cards_session_id_card_id");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_session_cards_session_id_position");

                    b.ToTable("session_cards", "lingohop");
                });

            modelBuilder.Entity("LingoHop.Domain.Study.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<int>("ExperienceEarned")
                        .HasColumnType("integer")
                        .HasColumnName("experience_earned");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId", "DeckId", "Status")
                        .HasDatabaseName("ix_study_sessions_user_id_deck_id_status");

                    b.ToTable("study_sessions", "lingohop");
                });

            modelBuilder.Entity("LingoHop.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DailyGoalCards")
                        .HasColumnType("integer")
                        .HasColumnName("daily_goal_cards");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DailyProgress", "LingoHop.Domain.Users.User.DailyProgress#DailyProgress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CardsReviewed")
                                .HasColumnType("integer")
                                .HasColumnName("daily_progress_cards_reviewed");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date")
                                .HasColumnName("daily_progress_date");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "LingoHop.Domain.Users.User.Profile#TelegramProfile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LanguageCode")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("language_code");

                            b1.Property<string>("LastName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Username")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("username");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Streak", "LingoHop.Domain.Users.User.Streak#StudyStreak", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Current")
                                .HasColumnType("integer")
                                .HasColumnName("streak_current");

                            b1.Property<DateOnly?>("LastStudiedOn")
                                .HasColumnType("date")
                                .HasColumnName("streak_last_studied_on");

                            b1.Property<int>("Longest")
                                .HasColumnType("integer")
                                .HasColumnName("streak_longest");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id");

                    b.ToTable("users", "lingohop");
                });

            modelBuilder.Entity("LingoHop.Domain.Decks.Card", b =>
                {
                    b.HasOne("LingoHop.Domain.Decks.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingoHop.Domain.Decks.Deck", b =>
                {
                    b.HasOne("LingoHop.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingoHop.Domain.Study.SessionCard", b =>
                {
                    b.HasOne("LingoHop.Domain.Study.StudySession", null)
                        .WithMany("Cards")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingoHop.Domain.Study.StudySession", b =>
                {
                    b.HasOne("LingoHop.Domain.Decks.Deck", null)
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LingoHop.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingoHop.Domain.Decks.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LingoHop.Domain.Study.StudySession", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
